### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by carolramsey** [ChristyTran/cs373-idb#2]
Create class diagram for song, album and artist.

**Comment by christyasyn** [comment]
Completed. Need to add to wiki. https://www.gliffy.com/go/share/smm5axln3exc4icvr5qt

**Comment by christyasyn** [comment]
Need to convert to yuml picture. Need to replace in wiki.

**Comment by carolramsey** [comment]
yUML diagram done, links (for view and edit) are in GitHub Wiki technical doc
